import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1789744019982 implements MigrationInterface {
  name = 'InitialSchema1789744019982';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "alert_delivery_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "alert_delivery_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_d5b00f309f07e21519f206fded8" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "alert_kinds" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(30) NOT NULL, CONSTRAINT "alert_kinds_code_key" UNIQUE ("code"), CONSTRAINT "PK_0fd355bdc0206bdcdd3576849ce" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tenant_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "tenant_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_f318eeaa611892309470ae9474e" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "tenants" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(255) NOT NULL, "status_id" integer NOT NULL DEFAULT '1', "timezone" character varying(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_tenants_status" ON "tenants" ("status_id") `);
    await queryRunner.query(
      `CREATE TABLE "alerts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "kind_id" integer NOT NULL, "subject_id" integer NOT NULL, "delivery_status_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_alerts_kind_subject" UNIQUE ("tenant_id", "kind_id", "subject_id"), CONSTRAINT "PK_60f895662df096bfcdfab7f4b96" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_alerts_tenant" ON "alerts" ("tenant_id") `);
    await queryRunner.query(
      `CREATE TABLE "customer_segments" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "customer_segments_code_key" UNIQUE ("code"), CONSTRAINT "PK_1509398a6c472bfecd14d9d3152" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "customers" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "name" character varying(255) NOT NULL, "company_name" character varying(255), "contact" character varying(255), "address" character varying(500), "segment_id" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_customers_tenant" ON "customers" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_customers_segment" ON "customers" ("segment_id") `);
    await queryRunner.query(
      `CREATE TABLE "contract_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "contract_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_ed0b693e79477280c5a97e9b1e0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "contracts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "customer_id" integer NOT NULL, "signed_at" date NOT NULL, "expires_at" date NOT NULL, "status_id" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c7b8f3a7b1acdd49497d83d0fb" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_contracts_tenant" ON "contracts" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_contracts_customer" ON "contracts" ("customer_id") `);
    await queryRunner.query(`CREATE INDEX "idx_contracts_expires_at" ON "contracts" ("expires_at") `);
    await queryRunner.query(`CREATE INDEX "idx_contracts_status" ON "contracts" ("status_id") `);
    await queryRunner.query(
      `CREATE TABLE "employee_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "employee_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_002adb1bf8f8e84e808e753e450" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "roles" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(50) NOT NULL, CONSTRAINT "roles_code_key" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "teams" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_teams_tenant_code" UNIQUE ("tenant_id", "code"), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_teams_tenant" ON "teams" ("tenant_id") `);
    await queryRunner.query(
      `CREATE TABLE "employees" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "name" character varying(255) NOT NULL, "contact" character varying(255), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "manager_id" integer, "team_id" integer, "role_id" integer NOT NULL, "status_id" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_employees_email" UNIQUE ("email"), CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_employees_tenant" ON "employees" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_employees_manager" ON "employees" ("manager_id") `);
    await queryRunner.query(`CREATE INDEX "idx_employees_team" ON "employees" ("team_id") `);
    await queryRunner.query(`CREATE INDEX "idx_employees_status" ON "employees" ("status_id") `);
    await queryRunner.query(
      `CREATE TABLE "cost_categories" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "cost_categories_code_key" UNIQUE ("code"), CONSTRAINT "PK_7a64898fa80f0cd6ec029d227d0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "contract_costs" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "contract_id" integer NOT NULL, "category_id" integer NOT NULL, "period" date NOT NULL, "amount" numeric(14,2) NOT NULL, "created_by" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_contract_costs_period" UNIQUE ("contract_id", "category_id", "period"), CONSTRAINT "ck_contract_costs_period_is_month_start" CHECK (period = date_trunc('month', period)::date), CONSTRAINT "PK_e55e0dedd6de2b751628551b6ad" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_contract_costs_tenant" ON "contract_costs" ("tenant_id") `);
    await queryRunner.query(
      `CREATE INDEX "idx_contract_costs_contract" ON "contract_costs" ("contract_id") `,
    );
    await queryRunner.query(`CREATE INDEX "idx_contract_costs_period" ON "contract_costs" ("period") `);
    await queryRunner.query(
      `CREATE TABLE "frequency_units" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "frequency_units_code_key" UNIQUE ("code"), CONSTRAINT "PK_2cace0bcb832432272fc5fa45fe" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "contract_sites" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "contract_id" integer NOT NULL, "name" character varying(255) NOT NULL, "work_requirements" character varying(2000), "notes" character varying(2000), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4ffd5edbf14834b86b16d6d8f6" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_contract_sites_tenant" ON "contract_sites" ("tenant_id") `);
    await queryRunner.query(
      `CREATE INDEX "idx_contract_sites_contract" ON "contract_sites" ("contract_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "contract_items" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "site_id" integer NOT NULL, "name" character varying(255) NOT NULL, "frequency_count" integer NOT NULL, "frequency_unit_id" integer NOT NULL, "frequency_rule" character varying(255), "unit_price" numeric(14,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_490c7394f3b09ee92c41668a156" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_contract_items_tenant" ON "contract_items" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_contract_items_site" ON "contract_items" ("site_id") `);
    await queryRunner.query(
      `CREATE TABLE "photo_types" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "photo_types_code_key" UNIQUE ("code"), CONSTRAINT "PK_4c51d9fc8aeb365311633fc5cf7" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "shift_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "shift_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_e5274b04522952ba2de4ecd3811" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "statement_statuses" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" character varying(20) NOT NULL, CONSTRAINT "statement_statuses_code_key" UNIQUE ("code"), CONSTRAINT "PK_f0cfae21d60847ee6f9e7cd5ca7" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "platform_admins" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "platform_admins_username_key" UNIQUE ("username"), CONSTRAINT "PK_faecb3398d1962507b44c76e4f0" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "shifts" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "contract_item_id" integer NOT NULL, "assignee_id" integer, "scheduled_date" date NOT NULL, "completed_at" TIMESTAMP, "status_id" integer NOT NULL DEFAULT '1', "latitude" numeric(9,6), "longitude" numeric(9,6), "captured_at" TIMESTAMP, "receipt_photo_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_shifts_tenant" ON "shifts" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_shifts_contract_item" ON "shifts" ("contract_item_id") `);
    await queryRunner.query(`CREATE INDEX "idx_shifts_assignee" ON "shifts" ("assignee_id") `);
    await queryRunner.query(`CREATE INDEX "idx_shifts_scheduled_date" ON "shifts" ("scheduled_date") `);
    await queryRunner.query(`CREATE INDEX "idx_shifts_status" ON "shifts" ("status_id") `);
    await queryRunner.query(
      `CREATE TABLE "shift_photos" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "shift_id" integer NOT NULL, "type_id" integer NOT NULL, "url" character varying(500) NOT NULL, "captured_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f9720b918ee50d95b7c1582beb9" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_shift_photos_tenant" ON "shift_photos" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_shift_photos_shift" ON "shift_photos" ("shift_id") `);
    await queryRunner.query(`CREATE INDEX "idx_shift_photos_type" ON "shift_photos" ("type_id") `);
    await queryRunner.query(
      `CREATE TABLE "statements" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tenant_id" integer NOT NULL, "contract_id" integer NOT NULL, "period" date NOT NULL, "total_amount" numeric(14,2) NOT NULL DEFAULT '0', "status_id" integer NOT NULL DEFAULT '1', "pdf_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_statements_contract_period" UNIQUE ("contract_id", "period"), CONSTRAINT "ck_statements_period_is_month_start" CHECK (period = date_trunc('month', period)::date), CONSTRAINT "PK_7f53bcddeb706df7ea7eec10b8d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "idx_statements_tenant" ON "statements" ("tenant_id") `);
    await queryRunner.query(`CREATE INDEX "idx_statements_contract" ON "statements" ("contract_id") `);
    await queryRunner.query(`CREATE INDEX "idx_statements_status" ON "statements" ("status_id") `);
    await queryRunner.query(
      `ALTER TABLE "tenants" ADD CONSTRAINT "fk_tenants_status" FOREIGN KEY ("status_id") REFERENCES "tenant_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alerts" ADD CONSTRAINT "fk_alerts_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alerts" ADD CONSTRAINT "fk_alerts_kind" FOREIGN KEY ("kind_id") REFERENCES "alert_kinds"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alerts" ADD CONSTRAINT "fk_alerts_delivery_status" FOREIGN KEY ("delivery_status_id") REFERENCES "alert_delivery_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "customers" ADD CONSTRAINT "fk_customers_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "customers" ADD CONSTRAINT "fk_customers_segment" FOREIGN KEY ("segment_id") REFERENCES "customer_segments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contracts" ADD CONSTRAINT "fk_contracts_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contracts" ADD CONSTRAINT "fk_contracts_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contracts" ADD CONSTRAINT "fk_contracts_status" FOREIGN KEY ("status_id") REFERENCES "contract_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "teams" ADD CONSTRAINT "fk_teams_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_manager" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_team" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "employees" ADD CONSTRAINT "fk_employees_status" FOREIGN KEY ("status_id") REFERENCES "employee_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_costs" ADD CONSTRAINT "fk_contract_costs_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_costs" ADD CONSTRAINT "fk_contract_costs_contract" FOREIGN KEY ("contract_id") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_costs" ADD CONSTRAINT "fk_contract_costs_category" FOREIGN KEY ("category_id") REFERENCES "cost_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_costs" ADD CONSTRAINT "fk_contract_costs_created_by" FOREIGN KEY ("created_by") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_sites" ADD CONSTRAINT "fk_contract_sites_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_sites" ADD CONSTRAINT "fk_contract_sites_contract" FOREIGN KEY ("contract_id") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_items" ADD CONSTRAINT "fk_contract_items_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_items" ADD CONSTRAINT "fk_contract_items_site" FOREIGN KEY ("site_id") REFERENCES "contract_sites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "contract_items" ADD CONSTRAINT "fk_contract_items_frequency_unit" FOREIGN KEY ("frequency_unit_id") REFERENCES "frequency_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shifts" ADD CONSTRAINT "fk_shifts_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shifts" ADD CONSTRAINT "fk_shifts_contract_item" FOREIGN KEY ("contract_item_id") REFERENCES "contract_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shifts" ADD CONSTRAINT "fk_shifts_assignee" FOREIGN KEY ("assignee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shifts" ADD CONSTRAINT "fk_shifts_status" FOREIGN KEY ("status_id") REFERENCES "shift_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shift_photos" ADD CONSTRAINT "fk_shift_photos_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shift_photos" ADD CONSTRAINT "fk_shift_photos_shift" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shift_photos" ADD CONSTRAINT "fk_shift_photos_type" FOREIGN KEY ("type_id") REFERENCES "photo_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "statements" ADD CONSTRAINT "fk_statements_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "statements" ADD CONSTRAINT "fk_statements_contract" FOREIGN KEY ("contract_id") REFERENCES "contracts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "statements" ADD CONSTRAINT "fk_statements_status" FOREIGN KEY ("status_id") REFERENCES "statement_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`
            INSERT INTO tenant_statuses (code) VALUES ('active'), ('suspended');
            INSERT INTO roles (code) VALUES ('director'), ('accountant'), ('manager'), ('team_lead'), ('employee');
            INSERT INTO customer_segments (code) VALUES ('regular'), ('vip');
            INSERT INTO employee_statuses (code) VALUES ('active'), ('terminated');
            INSERT INTO contract_statuses (code) VALUES ('active'), ('expired'), ('cancelled'), ('renewed');
            INSERT INTO shift_statuses (code) VALUES ('scheduled'), ('late'), ('completed'), ('disputed');
            INSERT INTO frequency_units (code) VALUES ('day'), ('week'), ('month'), ('quarter'), ('year');
            INSERT INTO cost_categories (code) VALUES ('labor'), ('materials'), ('other');
            INSERT INTO photo_types (code) VALUES ('before'), ('after');
            INSERT INTO alert_kinds (code) VALUES ('contract_expiring'), ('shift_overdue');
            INSERT INTO alert_delivery_statuses (code) VALUES ('sent'), ('not_sent'), ('fallback');
            INSERT INTO statement_statuses (code) VALUES ('draft'), ('issued'), ('sent');
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "statements" DROP CONSTRAINT "fk_statements_status"`);
    await queryRunner.query(`ALTER TABLE "statements" DROP CONSTRAINT "fk_statements_contract"`);
    await queryRunner.query(`ALTER TABLE "statements" DROP CONSTRAINT "fk_statements_tenant"`);
    await queryRunner.query(`ALTER TABLE "shift_photos" DROP CONSTRAINT "fk_shift_photos_type"`);
    await queryRunner.query(`ALTER TABLE "shift_photos" DROP CONSTRAINT "fk_shift_photos_shift"`);
    await queryRunner.query(`ALTER TABLE "shift_photos" DROP CONSTRAINT "fk_shift_photos_tenant"`);
    await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "fk_shifts_status"`);
    await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "fk_shifts_assignee"`);
    await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "fk_shifts_contract_item"`);
    await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "fk_shifts_tenant"`);
    await queryRunner.query(
      `ALTER TABLE "contract_items" DROP CONSTRAINT "fk_contract_items_frequency_unit"`,
    );
    await queryRunner.query(`ALTER TABLE "contract_items" DROP CONSTRAINT "fk_contract_items_site"`);
    await queryRunner.query(`ALTER TABLE "contract_items" DROP CONSTRAINT "fk_contract_items_tenant"`);
    await queryRunner.query(`ALTER TABLE "contract_sites" DROP CONSTRAINT "fk_contract_sites_contract"`);
    await queryRunner.query(`ALTER TABLE "contract_sites" DROP CONSTRAINT "fk_contract_sites_tenant"`);
    await queryRunner.query(`ALTER TABLE "contract_costs" DROP CONSTRAINT "fk_contract_costs_created_by"`);
    await queryRunner.query(`ALTER TABLE "contract_costs" DROP CONSTRAINT "fk_contract_costs_category"`);
    await queryRunner.query(`ALTER TABLE "contract_costs" DROP CONSTRAINT "fk_contract_costs_contract"`);
    await queryRunner.query(`ALTER TABLE "contract_costs" DROP CONSTRAINT "fk_contract_costs_tenant"`);
    await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "fk_employees_status"`);
    await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "fk_employees_role"`);
    await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "fk_employees_team"`);
    await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "fk_employees_manager"`);
    await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "fk_employees_tenant"`);
    await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "fk_teams_tenant"`);
    await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "fk_contracts_status"`);
    await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "fk_contracts_customer"`);
    await queryRunner.query(`ALTER TABLE "contracts" DROP CONSTRAINT "fk_contracts_tenant"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "fk_customers_segment"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "fk_customers_tenant"`);
    await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "fk_alerts_delivery_status"`);
    await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "fk_alerts_kind"`);
    await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "fk_alerts_tenant"`);
    await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "fk_tenants_status"`);
    await queryRunner.query(`DROP INDEX "public"."idx_statements_status"`);
    await queryRunner.query(`DROP INDEX "public"."idx_statements_contract"`);
    await queryRunner.query(`DROP INDEX "public"."idx_statements_tenant"`);
    await queryRunner.query(`DROP TABLE "statements"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shift_photos_type"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shift_photos_shift"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shift_photos_tenant"`);
    await queryRunner.query(`DROP TABLE "shift_photos"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shifts_status"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shifts_scheduled_date"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shifts_assignee"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shifts_contract_item"`);
    await queryRunner.query(`DROP INDEX "public"."idx_shifts_tenant"`);
    await queryRunner.query(`DROP TABLE "shifts"`);
    await queryRunner.query(`DROP TABLE "platform_admins"`);
    await queryRunner.query(`DROP TABLE "statement_statuses"`);
    await queryRunner.query(`DROP TABLE "shift_statuses"`);
    await queryRunner.query(`DROP TABLE "photo_types"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_items_site"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_items_tenant"`);
    await queryRunner.query(`DROP TABLE "contract_items"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_sites_contract"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_sites_tenant"`);
    await queryRunner.query(`DROP TABLE "contract_sites"`);
    await queryRunner.query(`DROP TABLE "frequency_units"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_costs_period"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_costs_contract"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contract_costs_tenant"`);
    await queryRunner.query(`DROP TABLE "contract_costs"`);
    await queryRunner.query(`DROP TABLE "cost_categories"`);
    await queryRunner.query(`DROP INDEX "public"."idx_employees_status"`);
    await queryRunner.query(`DROP INDEX "public"."idx_employees_team"`);
    await queryRunner.query(`DROP INDEX "public"."idx_employees_manager"`);
    await queryRunner.query(`DROP INDEX "public"."idx_employees_tenant"`);
    await queryRunner.query(`DROP TABLE "employees"`);
    await queryRunner.query(`DROP INDEX "public"."idx_teams_tenant"`);
    await queryRunner.query(`DROP TABLE "teams"`);
    await queryRunner.query(`DROP TABLE "roles"`);
    await queryRunner.query(`DROP TABLE "employee_statuses"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contracts_status"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contracts_expires_at"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contracts_customer"`);
    await queryRunner.query(`DROP INDEX "public"."idx_contracts_tenant"`);
    await queryRunner.query(`DROP TABLE "contracts"`);
    await queryRunner.query(`DROP TABLE "contract_statuses"`);
    await queryRunner.query(`DROP INDEX "public"."idx_customers_segment"`);
    await queryRunner.query(`DROP INDEX "public"."idx_customers_tenant"`);
    await queryRunner.query(`DROP TABLE "customers"`);
    await queryRunner.query(`DROP TABLE "customer_segments"`);
    await queryRunner.query(`DROP INDEX "public"."idx_alerts_tenant"`);
    await queryRunner.query(`DROP TABLE "alerts"`);
    await queryRunner.query(`DROP INDEX "public"."idx_tenants_status"`);
    await queryRunner.query(`DROP TABLE "tenants"`);
    await queryRunner.query(`DROP TABLE "tenant_statuses"`);
    await queryRunner.query(`DROP TABLE "alert_kinds"`);
    await queryRunner.query(`DROP TABLE "alert_delivery_statuses"`);
  }
}
